ARG base_image=uvilla/tps-env-ls6:latest

FROM ${base_image}
MAINTAINER Umberto Villa <uvilla@oden.utexas.edu>

ARG make_cores=6
ARG cuda_arch=sm_80

RUN git clone https://github.com/pecos/tps \
    && cd tps \
    && git checkout boltzmann-integration \
    && git clone https://github.com/ut-padas/boltzmann \
    && git clone https://github.com/pecos/tps-inputs \
    && cd tps-inputs \
    && git checkout boltzmann-integration

RUN source scl_source enable gcc-toolset-11 && \
    cd tps \
    && ./bootstrap \
    && mkdir build-gpu \
    && cd build-gpu \
    && ../configure CUDA_ARCH=$cuda_arch --disable-valgrind --enable-gpu-cuda --enable-pybind11 CPPFLAGS=-I$(python3 -c "import pybind11; print(pybind11.get_include())") \
    && make -j $make_cores \
    && make -j $make_cores  check TESTS="vpath.sh"